<?php
/**
 * Template Name: Imajiner - Example
 *
 * Reference template that follows the Imajiner template contract.
 *
 * @package Imajiner
 */

get_header();
?>

<!-- imj:section name="hero" -->
<section class="hero">
	<div class="container">
		<h1  class="hero_new test_class">Build pages your team can actually edits</h1>
		<p class="hero__text">This page is a plain PHP template. The Imajiner Editor reads it, lets you change it visually, and writes the PHP back.</p>
		<a class="button" href="<?php echo esc_url( home_url( '/contact/' ) ); ?>">Get in touch</a>
		<img class="hero__image" src="http://imajiner-wordpress-editor.test/wp-content/uploads/2026/10/imajiner-hero.png" alt="Diagonal stripes on blue" width="1200" height="600">
	</div>
</section>
<!-- /imj:section -->

<!-- imj:section name="features" -->
<section class="features">
	<div class="container features__grid">
		<div class="feature">
			<h2 class="feature__title">Generated by AI</h2>
			<p class="feature__text">Start from a prompt and get a template that follows the contract.</p>
		</div>
		<div class="feature">
			<h2 class="feature__title">Edited by hand</h2>
			<p class="feature__text">Change text, images, links and styles without touching code.</p>
		</div>
		<div class="feature">
			<h2 class="feature__title">Still just PHP</h2>
			<p class="feature__text">Loops and queries stay intact, and the file stays readable in git.</p>
		</div>
	</div>
</section>
<!-- /imj:section -->

<!-- imj:section name="latest-posts" -->
<section class="latest-posts">
	<div class="container">
		<h2 class="latest-posts__title">Latest posts</h2>
		<?php
		$imj_latest = new WP_Query(
			array(
				'posts_per_page'      => 3,
				'ignore_sticky_posts' => true,
			)
		);
		?>
		<?php if ( $imj_latest->have_posts() ) : ?>
			<div class="post-list">
				<?php while ( $imj_latest->have_posts() ) : ?>
					<?php $imj_latest->the_post(); ?>
					<article class="post-card">
						<h3 class="post-card__title"><a class="test" href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h3>
						<p class="post-card__excerpt test_test"><?php echo esc_html( get_the_excerpt() ); ?></p>
					</article>
				<?php endwhile; ?>
			</div>
			<?php wp_reset_postdata(); ?>
		<?php endif; ?>
	</div>
</section>
<!-- /imj:section -->

<?php
get_footer();
